domain: tw.treadmill
treadmill_version: 0.1.0
master:
  name: treadmillmaster
  exact_count: 3
  instance_type: small
node_server:
  name: treadmillnodeserver
  exact_count: 1
  instance_type: xlarge
freeipa_server:
  name: treadmillfreeipa
  exact_count: 1
  instance_type: small
  realm: TW.TREADMILL
  server_hostname: ipa
  authentication: simple # sasl or simple
  local_admin_pwd_file: ~/.treadmill/.ldap
  remote_admin_pwd_file: /home/treadmld/.treadmill_ldap

