---
- name: Spinup the instance
  ec2:
    exact_count: "{{ exact_count }}"
    vpc_subnet_id: "{{ subnet_id }}"
    region: "{{ vpc_region }}"
    image: "{{ ami_id }}"
    instance_type: t2.micro
    key_name: "{{ aws_key_name }}"
    count_tag:
      Name: "{{ instance_name }}"
    instance_tags: { "Name":"{{ instance_name }}" }
    group_id: "{{ sg_info.group_id }}"
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: 10
        delete_on_termination: true
    wait: yes
  register: created_instances

- name: Associate provided elastic IP
  ec2_eip:
    region: "{{ vpc_region }}"
    device_id: "{{created_instances.tagged_instances[0].id}}"
