---
- name: Fetch VPC Subnet Facts
  ec2_vpc_subnet_facts:
    filters:
      "tag:Name": "{{ vpc_name }}"
    region: "{{ vpc_region }}"
  register: subnet_facts
- set_fact:
    subnet_id: "{{ subnet_facts.subnets[0].id }}"
  when: subnet_facts.subnets[0].tags.Name == "{{ subnet_name }}"