---
# tasks file for master
- hosts: controller
  tasks:
    - name: Include config
      include_vars: ../../../aws.properties
    - name: Fetch EC2 Facts
      ec2_remote_facts:
        filters:
          instance-state-name: running
          "tag:Name": "{{ instance_name }}"
        region: "{{ vpc_region }}"
      register: instance_facts

    - name: Display all variables/facts known for a host
      debug:
        msg: "{{ instance_facts.instances }}"

    - add_host:
        groupname=ec2instances
        hostname="{{item.public_ip_address}}"
        instance_tags="{{item.tags}}"
      with_items: "{{instance_facts.instances}}"

- hosts: ec2instances
  tasks:
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest